### ISSUE TITLE
In generate slice request, update before removing unused object groups

### ISSUE THREAD

**Issue by dorienmc** [PRINTR3D/formide-tools#15]
When the print job tells that a feature (eg. raft) is not used, it is first removed and then the complete slice profile is updated (which adds it, because it was missing).
This means that 
- dynamic objects will be missing in the slice request.
- formide-tools might break when you are overriding parameters of unused features (which you actually should not).

A better way is to first update the slice profile and then remove the unused features, Katana will add a default feature for the non mandatory features (fan, raft, support ...) and actually set their use to false.

Note: There is one feature which katana desktop can set to unused but is mandatory in Katana -> the bed (when its unheatable). The bed size is however retrieved from the printer-object (in the slice job), so we should just add temperatures of zero.

**Comment by dorienmc** [comment]
Update: 
The slice profile is updated before going to the print job. Changing the override function to work per parameter group (called feature in the previous post) I solved the problem. The bed is never completely removed, so that is not a problem either.
We do need to perform the sliceRequest.override() function after all the other 'generateSettings' functions (but I will do a pull request at the formide-api for that).

**Comment by ChrisTerBeke** [comment]
keep in mind that the client also uses this package, so whenever updating things, not only check the api implementation but also the client implementation (and do needed pull requests on both repo's)

**Comment by dorienmc** [comment]
Ah good point.
Note: In this case its just changing the order in which the functions are run, so it won't break extra things (though it is handy to keep them the same).

**Comment by dorienmc** [comment]
Both api and client are updated, override now happens at the end.
