### ISSUE TITLE
Add option to add string in recalculate

### ISSUE THREAD

**Issue by dorienmc** [PRINTR3D/formide-tools#24]
The mathjs math.eval function is able to evaluate things like 
```
(a == 0) ? \"some_value\" : \"some other value\"
```

The strings are however not escaped correctly in  the update slice profile function.
For example, the 'recalculate' expression 
```
"{({sliceProfile.support.pattern} == 0) ? \"SUPPORT_GRID\" : \"SUPPORT_LINES\"}"
```
Gives the error
```
throw createSyntaxError('Syntax error in part "' + token + '"');
    ^

SyntaxError: Syntax error in part "{({sliceProfile.support.pattern} == 0) ? "SUPPORT_GRID" : "SUPPORT_LINES"}" (char 1)
```
I.e. it seems that the strings are escaped to early.

**Comment by ChrisTerBeke** [comment]
You can try using a single quote (') for the values. Javascript also uses single quotes for strings (so you can use these nested).

**Comment by dorienmc** [comment]
The problem is that mathjs does not.

**Comment by ChrisTerBeke** [comment]
schrale bende :P

**Comment by dorienmc** [comment]
Added to development-dorien branch. Should I pull-request this to development or master?

**Comment by ChrisTerBeke** [comment]
development, then I'll look it over. Do the tests work?

**Comment by dorienmc** [comment]
It did before merging development into development-dorien, and now it does again. Forgot to do a pull request, but I did merge development into development-dorien and tested that extensively.

Note that it now also tests dynamic parameters if they exist (when mandatory and only in slice request), and if they are within bounds. So that might give some errors we did not find before (which means they were wrong all that time, it just wasn't tested before).

**Comment by dorienmc** [comment]
Note: Because of stringifying and parsing the json file the escape character trick does not work!

Fix: I made a new 'escape' character for string values. If you add a string between brackets and it does not start with 'sliceProfile' formide tools will parse it to a string. I.e.
`"{({sliceProfile.support.pattern} == 0) ? {SUPPORT_GRID} : {SUPPORT_LINES}}"`
will be parsed to (assuming sliceProfile.support.pattern is 1)
`{(1 == 0) ? "SUPPORT_GRID" : "SUPPORT_LINES"}`

Currently added this to dev-dorien, and it works with npm test. But for the front-end its still a by trial and error process, although I assume this will work as its now all one string.

**Comment by dorienmc** [comment]
This is added to all branches, but not used in any reference file yet.
I will do this after all the demo's.

**Comment by dorienmc** [comment]
Moved to JIRA, see NAT-119
