### ISSUE TITLE
Check if type is correct

### ISSUE THREAD

**Issue by dorienmc** [PRINTR3D/formide-tools#37]
The reference file tells which type a value should have, this is not checked in formide-tools

**Comment by dorienmc** [comment]
Added this to dev-dorien. It currently only gives a warning.
Should we warn and set the value to default or should we create an assertion error?

**Comment by ChrisTerBeke** [comment]
See other issue :)

**Comment by dorienmc** [comment]
See also issue #38 

All non-dynamic input is now checked in `updateSliceProfile` and all parameters are checked in `generateSliceRequest`. Parameters are checked (in `testParam.js`) on type, range (if a min/max value is given) or list (if list options are given). In case the parameter is deemed invalid a warning is given (error console only currently) and the value is set to default. 

In `generateSliceRequest` override parameters are also checked, they are ignored when deemed invalid (using the same function as above).

> This is currently implemented in the branch `feature/restructure`

**Comment by dorienmc** [comment]
Moved to JIRA, NAT-118
