### ISSUE TITLE
Check if value is in given options list

### ISSUE THREAD

**Issue by dorienmc** [PRINTR3D/formide-tools#38]
The infill pattern (and others) have a list of possible values, until now this was not checked in formide-tools

**Comment by dorienmc** [comment]
Added this to dev-dorien. It currently only gives a warning.
Should we warn and set the value to default or should we create an assertion error?

**Comment by ChrisTerBeke** [comment]
Probably best to throw an error since you might be slicing with parameters you don't want (plus the API or interface somehow constructed an incorrect parameter set anyways otherwise the type would be correct).

**Comment by dorienmc** [comment]
Shall I do this in update slice profile (so only non-dynamic) or in generate slice request?

**Comment by ChrisTerBeke** [comment]
nicest ofc would be to check all input, also the dynamic ones if they exist

**Comment by dorienmc** [comment]
All non-dynamic input is now checked in `updateSliceProfile` and all parameters are checked in `generateSliceRequest`. Parameters are checked (in `testParam.js`) on type, range (if a min/max value is given) or list (if list options are given). In case the parameter is deemed invalid a warning is given (error console only currently) and the value is set to default. 

In `generateSliceRequest` override parameters are also checked, they are ignored when deemed invalid (using the same function as above).

> This is currently implemented in the branch `feature/restructure`

**Comment by dorienmc** [comment]
Moved to JIRA, NAT-117
